2020-03-09 10:42:51 [ ERROR ] [ LoggingFailureAnalysisReporter.java :42(report)] 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method shiroCacheManager in cn.jeeweb.bbs.config.ShiroConfig required a bean of type 'org.springframework.cache.ehcache.EhCacheCacheManager' that could not be found.
	- Bean method 'cacheManager' not loaded because Cache org.springframework.boot.autoconfigure.cache.EhCacheCacheConfiguration unknown cache type


Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.cache.ehcache.EhCacheCacheManager' in your configuration.

2020-03-09 10:43:02 [ ERROR ] [ LoggingFailureAnalysisReporter.java :42(report)] 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method shiroCacheManager in cn.jeeweb.bbs.config.ShiroConfig required a bean of type 'org.springframework.cache.ehcache.EhCacheCacheManager' that could not be found.
	- Bean method 'cacheManager' not loaded because Cache org.springframework.boot.autoconfigure.cache.EhCacheCacheConfiguration unknown cache type


Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.cache.ehcache.EhCacheCacheManager' in your configuration.

2020-03-09 10:49:12 [ ERROR ] [ LoggingFailureAnalysisReporter.java :42(report)] 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method shiroCacheManager in cn.jeeweb.bbs.config.ShiroConfig required a bean of type 'org.springframework.cache.ehcache.EhCacheCacheManager' that could not be found.
	- Bean method 'cacheManager' not loaded because Cache org.springframework.boot.autoconfigure.cache.EhCacheCacheConfiguration unknown cache type


Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.cache.ehcache.EhCacheCacheManager' in your configuration.

2020-03-09 10:54:27 [ ERROR ] [ LoggingFailureAnalysisReporter.java :42(report)] 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method sessionDAO in cn.jeeweb.bbs.config.ShiroConfig required a bean of type 'org.springframework.data.redis.core.RedisTemplate' that could not be found.
	- Bean method 'redisTemplate' not loaded because auto-configuration 'RedisAutoConfiguration' was excluded
	- Bean method 'stringRedisTemplate' not loaded because auto-configuration 'RedisAutoConfiguration' was excluded


Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.data.redis.core.RedisTemplate' in your configuration.

2020-03-09 11:12:26 [ ERROR ] [ DruidDataSource.java :1190(handleConnectionException)] discard connection
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 83,889 milliseconds ago.  The last packet sent successfully to the server was 26,742 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3903)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4796)
	at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:681)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:283)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:474)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:289)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at cn.jeeweb.bbs.modules.task.service.impl.ScheduleJobLogServiceImpl$$EnhancerBySpringCGLIB$$306511fe.onStart(<generated>)
	at cn.jeeweb.common.quartz.factory.QuartzJobFactory.executeInternal(QuartzJobFactory.java:39)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3472)
	... 19 more
2020-03-12 16:48:31 [ ERROR ] [ LoggingFailureAnalysisReporter.java :42(report)] 

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 9083 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 9083, or configure this application to listen on another port.

